# Generated by Django 3.1.5 on 2021-01-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('ptype', models.CharField(max_length=10)),
                ('bdate', models.DateField()),
                ('rate', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
