# Generated by Django 3.1.5 on 2021-01-30 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0003_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='bdate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='sell',
            name='sdate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
