# Generated by Django 3.1.5 on 2021-01-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
